language: node_js

matrix:
  include:
      - node_js: 8
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='build'
        os: [linux, osx]
      - node_js: 8
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile test'
        os: [linux, osx]
      - node_js: 7
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
        os: [linux, osx]
      - node_js: 7
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'
      - node_js: 6
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
      - node_js: 6
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'
      - node_js: 5
        env:  NODE_ENVIRONMENT=production  BUILD_STEPS='compile test'
      - node_js: 5
        env:  NODE_ENVIRONMENT=development BUILD_STEPS='compile'

cache:
  directories:
    - node_modules

script:
  - if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then npm run build; fi
  - if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then npm run ${BUILD_STEPS}; fi
